spatial_dims: 3
in_channels: 3
out_channels: 3
num_res_blocks: 1
num_channels: (32, 64, 64)
attention_levels: (False, True, True)
num_head_channels: (0, 64, 64)
with_conditioning: False
cross_attention_dim: null